# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: dat@undercurrent.tech
author_name: phamdat
cloud_provider: vercel
contract_name: algo_track
deployment_language: python
preset_name: production
project_name: algo-track

